### ISSUE TITLE
Endpoints are not working last tried 28th aug

### ISSUE THREAD

**Issue by choxxin** [Ryuk-me/UMS-Api#2]
![Screenshot 2024-08-28 020317](https://github.com/user-attachments/assets/25a73ccd-0f61-4a14-96c7-e223f50ed11f)

**Comment by Ryuk-me** [comment]
@choxxin Thank you trying out this project, I've checked it now it's working. I was able to login and get user's details attaching screenshot as well. Could you please try again and let me know if its working.
![image](https://github.com/user-attachments/assets/56f9ab0e-6d04-4207-ae47-e75c3e4a8a97)

**Comment by choxxin** [comment]
Yes its working fine ,thank u soo much
